### ISSUE TITLE
Issue with JSON returned by OpenAI apparently

### ISSUE THREAD

**Issue by bloomsder** [SnyderConsulting/OpenAITools#7]
Thanks for the hard work, appreciated.  Just getting started but have an immediate issue

I am getting through the npm install OK now after downgrading to node 16, but when visiting the page, I get: 

`error - unhandledRejection: FetchError: invalid json response body at https://www.openaitools.com/api/files/get-files reason: Unexpected token I in JSON at position 0
`

**Comment by SnyderConsulting** [comment]
Thanks, it was hardcoded to use the deployed application's API path.

Added a new flag in Main.js "isLocalDevelopment", set that to true and the error is resolved.
